### ISSUE TITLE
chunked encoding output isn't working

### ISSUE THREAD

**Issue by unclejack** [williame/hellepoll#1]
Chrome throws an error if out_encoding_chunked isn't set to false all the time.
The same thing happens with curl.

This is what happens with and without the Content Length.

**Comment by unclejack** [comment]
It looks like the chunks weren't properly terminated.

This patch fixes the issue.

diff --git a/http.cpp b/http.cpp
index 8feb152..892d0cd 100644
--- a/http.cpp
+++ b/http.cpp
@@ -164,6 +164,8 @@ void HttpServerConnection::write(const void\* ptr,size_t len) {
        if(out_encoding_chunked)
                async_printf("%zx\r\n",len);
        async_write_cpy(ptr,len);
-       if(out_encoding_chunked)
- ```
            async_printf("\r\n");
  ```
  
  }
  
  void HttpServerConnection::write(const char\* str) {

**Comment by williame** [comment]
My sincere apologies; I had fixed this bug in another way in HTTP pipelining support; but this did not make it into a public repository.

**Comment by unclejack** [comment]
That's ok, thank you.

I'm going to look into other parts next.

**Comment by williame** [comment]
http://williamedwardscoder.tumblr.com/post/13590981677/performance-lessons-for-http-sockets might be interesting.

I wrote the HTTP handler in hellepoll the day before releasing hellepoll in order to make the helloworld work in the release; I would welcome any contributions of a clean-room HTTP handler for hellepoll with a proper per-request handler and regex or prefix splitting of requests etc and pipelining support etc.

**Comment by unclejack** [comment]
I'd like to do that. However, I could use more good documentation on the matter.

I was planning to add per request handling, a system for templates, a routing system and caching.

**Comment by williame** [comment]
http://williamedwardscoder.tumblr.com/post/17166532605/hellepoll-might-get-hacked - use the comments there to discuss vision, or move straight to the hellepoll wiki :)
